package charger

// Code generated by github.com/evcc-io/evcc/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/evcc-io/evcc/api"
)

func decorateHeidelbergEC(base *HeidelbergEC, phaseSwitcher func(int) error) api.Charger {
	switch {
	case phaseSwitcher == nil:
		return base

	case phaseSwitcher != nil:
		return &struct {
			*HeidelbergEC
			api.PhaseSwitcher
		}{
			HeidelbergEC: base,
			PhaseSwitcher: &decorateHeidelbergECPhaseSwitcherImpl{
				phaseSwitcher: phaseSwitcher,
			},
		}
	}

	return nil
}

type decorateHeidelbergECPhaseSwitcherImpl struct {
	phaseSwitcher func(int) error
}

func (impl *decorateHeidelbergECPhaseSwitcherImpl) Phases1p3p(phases int) error {
	return impl.phaseSwitcher(phases)
}
